//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Sauvegarde.View {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projet_Sauvegarde.View.fr", typeof(fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ajouter.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Au revoir.
        /// </summary>
        public static string byeBye {
            get {
                return ResourceManager.GetString("byeBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez vous lancer vos backup(s) ou en ajouter une nouvelle ? (ajouter|demarrer) \nVotre fichiers d&apos;état et de log sont sauvegarder dans le dossier EasySave à l&apos;adresse D:/EasySave.
        /// </summary>
        public static string chooseBetwwenAddOrStart {
            get {
                return ResourceManager.GetString("chooseBetwwenAddOrStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à complete.
        /// </summary>
        public static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à differentielle.
        /// </summary>
        public static string differential {
            get {
                return ResourceManager.GetString("differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le lien de la sauvegarde complète.
        /// </summary>
        public static string enterCompletePath {
            get {
                return ResourceManager.GetString("enterCompletePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le lien de la destination.
        /// </summary>
        public static string enterDestinationPath {
            get {
                return ResourceManager.GetString("enterDestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le nom de la sauvegarde complète.
        /// </summary>
        public static string enterNameCompleteBackup {
            get {
                return ResourceManager.GetString("enterNameCompleteBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le nom de la sauvegarde différientielle.
        /// </summary>
        public static string enterNameDifferentialBackup {
            get {
                return ResourceManager.GetString("enterNameDifferentialBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le lien de la source.
        /// </summary>
        public static string enterSourcePath {
            get {
                return ResourceManager.GetString("enterSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à quitter.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à demarrer.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez vous faire une sauvegarde complete, differentielle ou quitter ? (complete|differentielle|quitter).
        /// </summary>
        public static string typeSave {
            get {
                return ResourceManager.GetString("typeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue dans EasySafe, un programme pour gérer la sauvegarde de vos fichiers.
        /// </summary>
        public static string welcom {
            get {
                return ResourceManager.GetString("welcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La sauvegarde complète n&apos;existe pas.
        /// </summary>
        public static string wrongCompletePath {
            get {
                return ResourceManager.GetString("wrongCompletePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entré incorrecte (ajouter|demarrer).
        /// </summary>
        public static string wrongInputAddOrStart {
            get {
                return ResourceManager.GetString("wrongInputAddOrStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La destination n&apos;existe pas.
        /// </summary>
        public static string wrongInputDestination {
            get {
                return ResourceManager.GetString("wrongInputDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom entré est incorrecte.
        /// </summary>
        public static string wrongInputName {
            get {
                return ResourceManager.GetString("wrongInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La source n&apos;existe pas.
        /// </summary>
        public static string wrongInputSource {
            get {
                return ResourceManager.GetString("wrongInputSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez incorrecte (complete|differentiellle|quitter).
        /// </summary>
        public static string wrongInputType {
            get {
                return ResourceManager.GetString("wrongInputType", resourceCulture);
            }
        }
    }
}
